# stack version: 1.0.4
flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps: []
resolver: lts-5.9
ghc-options:
  "*": -optP-nostdinc -optP-I~/usr/static-nss-glibc/include -optl-nodefaultlibs -Wl,-rpath=~/usr/static-nss-glibc/lib -optl-L~/usr/static-nss-glibc/lib -lc -lgcc
