database:
  user:     "_env:MYSQL_USER:realrealgold"
  password: "_env:MYSQL_PASSWORD:realrealgold"
  host:     "_env:MYSQL_HOST:localhost"
  port:     "_env:MYSQL_PORT:3306"
  database: "_env:MYSQL_DATABASE:realrealgold_test"
  poolsize: "_env:MYSQL_POOLSIZE:10"
